# Generated by Django 3.2.7 on 2021-10-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, upload_to='contest/', verbose_name='포스터')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='행사제목')),
                ('content', models.CharField(max_length=5000, null=True, verbose_name='행사내용')),
                ('host', models.CharField(max_length=50, null=True, verbose_name='주최')),
                ('organizer', models.CharField(max_length=50, null=True, verbose_name='주관')),
                ('apply_field', models.CharField(max_length=50, null=True, verbose_name='응모분야')),
                ('apply_type', models.CharField(max_length=50, null=True, verbose_name='접수방법')),
                ('qualification', models.CharField(max_length=50, null=True, verbose_name='참가자격')),
                ('reward_type', models.CharField(max_length=50, null=True, verbose_name='시상종류')),
                ('reward_amount', models.CharField(max_length=50, null=True, verbose_name='시상금')),
                ('site', models.CharField(max_length=50, null=True, verbose_name='홈페이지')),
                ('start_date', models.DateField(verbose_name='접수기간(시작)')),
                ('end_date', models.DateField(verbose_name='접수기간(종료)')),
                ('contest_status', models.CharField(choices=[('before', '진행 예정'), ('progress', '진행 중'), ('end', '종료')], max_length=10, verbose_name='상태')),
            ],
        ),
    ]
