# Generated by Django 3.2.7 on 2021-10-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='content',
            field=models.TextField(null=True, verbose_name='행사내용'),
        ),
    ]
