# Generated by Django 3.2.7 on 2021-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='apply_field',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='apply_type',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='reward_type',
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_status',
            field=models.CharField(choices=[('before_register', '접수 전'), ('register', '접수 중'), ('before_progress', '진행 전'), ('progress', '진행 중'), ('end', '종료')], max_length=20, verbose_name='상태'),
        ),
    ]
