# Generated by Django 3.2.7 on 2021-10-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0002_alter_usersetting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='프로필 이미지'),
        ),
    ]
