# Generated by Django 3.2.7 on 2021-10-17 11:10

from django.db import migrations, models
import sonagi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0003_usersetting_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='profile',
            field=models.ImageField(blank=True, upload_to=sonagi.utils.RandomFileName('profile'), verbose_name='프로필 이미지'),
        ),
    ]
