# Generated by Django 3.2.7 on 2021-10-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='작성자 이메일')),
                ('title', models.CharField(max_length=100, verbose_name='한줄평')),
                ('content', models.CharField(max_length=2000, null=True, verbose_name='내용')),
                ('emotion', models.CharField(choices=[('G', '좋음'), ('N', '보통'), ('B', '별로'), ('C', '슬픔'), ('S', '놀람')], max_length=1, verbose_name='감정')),
                ('write_date', models.DateField(auto_now_add=True, verbose_name='작성 일자')),
                ('rewrite_date', models.DateField(auto_now=True, verbose_name='최종 수정 일자')),
            ],
        ),
    ]
